hotwax/import

src/services/UploadService.ts, src/types/index.ts
prepareUploadJsonPayload - prepared payload to be used for upload json request
uploadJsonFile - uploads json file for import
=> Implemented: service to prepare payload for upload and upload json file for import (#232z1wx)

src/components/ProductPopover.vue, src/theme/variables.css, src/views/OrderDetail.vue, src/views/PurchaseOrder.vue
=> Updated the UI

src/views/OrderDetail.vue
Description
Used ionViewDidEnter instead of mounted so that the facilities are updated everytime the page is navigated.
=> Fixed: facilities not updated on login & logout(#2adma3f)

src/views/PurchaseOrder.vue
Description:
Added interface popover so that it closes after the field is selected.
=> Added interface popover to close it after field select(#2adm9yq)

src/views/OrderDetail.vue, src/views/Search.vue, src/views/TimezoneModal.vue
Closes #
:- Worked on improving the code to assign input field to instance variable for searchbar.
Because when performing any action on search with enter key, the value of instance variable is set after the action is performed due to which wrong data is passed to API.
=> Improved: code to assign input field to instance variable for searchbar (#2cj8nc4).

src/store/modules/order/actions.ts, src/views/OrderDetail.vue, src/views/PurchaseOrder.vue
Description:
Updated the code to use hc facilityId when applying facility on PO details page
Additional change:
Handled the case when order state is empty on orderDetails page.
=> Updated the code to use hc facilityId when applying facility on PO details page(#2admaej)

src/components/Menu.vue
=> Improved code by displaying instance and current time zone in the bottom of the menu(#28u2prh)

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md
=> added pr and issue template

src/store/modules/product/actions.ts
=> Change console.log to console.error in actions.ts

src/views/OrderDetail.vue
Closes #77 
Updated code to open logs in a new tab for better user experience
- [x ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)
=> Fixed: Viewing upload logs should open in a new tab

package-lock.json, package.json
=> Upgraded Ionic to 6.2(#2zb17hz)

src/views/OrderDetail.vue
=> Fixed: alert displaying on PO upload(#30rz7pt)

src/views/OrderDetail.vue
=> Fixed: alert not displayed after first upload(#30rz7pt)

src/views/Settings.vue
=> Improved code to open external links in new tab and update sample date format on clicking save button(#31a00jh)

package-lock.json, package.json
=> Preparing for relase 1.1.0 (#31fnnzj)

package-lock.json, package.json
=> Updated: app to prepare for a patch release

package-lock.json, package.json, release-notes.md
=> Updated: the app version and release notes for next release

src/components/ProductPopover.vue, src/locales/en.json, src/store/modules/order/OrderState.ts, src/store/modules/order/actions.ts, src/store/modules/order/getters.ts, src/store/modules/order/index.ts, src/store/modules/order/mutations.ts, src/views/OrderDetail.vue
=> Support for multiple PO's(#85zrh08cn)

src/views/OrderDetail.vue
=> fix: disable alert on token expire(#85zrkepcp)

src/views/PurchaseOrder.vue
Closes #121 
Unwanted error is removed, also if we decide not to upload a file, current file says selected.
https://user-images.githubusercontent.com/62360781/210771585-d7e2f527-0222-4e1f-b999-24e7be973ba5.mov
=> Fixed: Re-clicking on Upload file button & cancelling it gives error(#85zrhfp4c)

src/components/MappingConfiguration.vue
=> Improved: margin styling to only apply on mobile device by wrapping buttons in div for desktop view(#85zrhcq56)

src/views/PurchaseOrder.vue
=> Changing the uploaded file resets all the selected values (#85zrgy0wx)

package-lock.json, package.json, release-notes.md
=> Updated: app version and release notes for minor release v2.3.0

src/store/modules/order/actions.ts
=> Fixed: save function when updating the missing product is not working

src/App.vue
=> Fixed: missing call for unathorised emit in App.vue (#85zrn0xfq)

package-lock.json, package.json
=> Updated: app for minor release

src/main.ts
=> Updated: default dateTime format(#85zrnzcpm)

src/components/BulkAdjustmentModal.vue, src/components/BulkInventoryAdjustmentModal.vue, src/components/MissingFacilitiesModal.vue, src/components/ProductPopover.vue
=> fix: Use ion-list in modals(#85zrptxr9)

package-lock.json, package.json
=> Updated: app version for patch release (2.4.1)

package-lock.json, package.json
=> Updated: app version for minor release (2.5.0)

src/store/modules/user/actions.ts
=> Fixed: Mapping not saved in case there are no previous mappings (#85zrv32ug)

package-lock.json, package.json, release-notes.md
=> Updated: app version for minor release (2.9.0)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v2.12.0)

src/components/Menu.vue
=> Improved: Indentation for menu component(#248)

src/views/InventoryReview.vue, src/views/PurchaseOrderReview.vue
=> Fixed: issue when redirecting to commerce after successfull upload of inventory or PO file(#268)

package.json
Closes #
Improved: Upgraded dxp-component package version to the latest (v1.12.2).
=> Improved: Upgraded dxp-component package version to the latest (v1.12.2).

package-lock.json, package.json
Closes #
Updated: app version for the minor release (v2.16.0).
=> Updated: app version for the minor release (v2.16.0).

package-lock.json, package.json
Closes #
Fixed: app version from v2.16.0 to v2.15.0.
=> Fixed: app version from v2.16.0 to v2.15.0.

src/views/InventoryReview.vue
Related Issue #275 
Added a column `comments` in the upload file for reset inventory
=> Implemented: support to pass comment when uploading reset inventory file(#275)

package-lock.json, package.json
=> Improved: app version in package and lock file for minor release(v2.17.0)

src/main.ts
#246
- Added a entry in `main` file to fix html tags not working in the translations.
=> Fixed: html tags not working in the translations (#246)

src/store/modules/util/actions.ts, src/views/ScheduledRestock.vue, src/views/ScheduledRestockReview.vue
#289 
- Replaced the externalFacilityId with facilityId while creating the shipment.
- Also replaced the payload parameter  from `externalDestinationFacilityId` to `destinationFacilityId`.
- Increased the viewSize while fetching the facilities from 50 to 250.
=> Improved: Replace externalFacilityId with facilityId in payload & increase the viewSize to 250 (#289)

package-lock.json, package.json
#298 
#
Updated: oms-api version to v1.15.1
=> Updated: oms-api version to v1.15.1 (#298)

package-lock.json, package.json
#
Upated: app version for patch release v2.18.1
=> Upated: app version for patch release v2.18.1

package-lock.json, package.json
=> Updated: app version for release v3.0.0

src/views/PurchaseOrder.vue
https://github.com/hotwax/dxp-components/issues/362
#
=> Improved: the field SHOPIFY_PROD_SKU has been deprecated thus removed it.

package-lock.json, package.json
=> Updated: app version for minor release v3.1.0
