src/views/TimezoneModal.vue
Closes #
:- Worked on improving the code to use keyUp event for enter button instead of 'ionInput' for timeZone search.
=> Improved: code to use enter instead of input for Timezone search (#2cj8zmd).

src/views/PurchaseOrder.vue, src/views/TimezoneModal.vue
Closes #70 
Refactored the code and improved readability by removing the use of v-bind and replacing it with shorthand instead.
=> Refactored: removed v-bind and used the shorthand instead (#2yma2j9)

src/components/ProductPopover.vue
Closes #74 
When reverting a parent product, all the child products are changed to the first child element. 
Updated the code to filter items based on parentProductId as well as productSKU for correct data.
=> Fixed: Reseting reverts to wrong info(#2yma5bp)

src/components/Menu.vue, src/views/OrderDetail.vue
Closes #78 
If the user switches to another page, like the settings page, while reviewing their PO, when they return to the upload screen they land on the file upload screen which is disorienting.
Implemented a pop up that warns the user that if they switch to another screen while reviewing their PO, that their changes will be lost and they'll have to restart.
[screen-recorder-fri-nov-04-2022-16-42-17.webm](https://user-images.githubusercontent.com/58461801/199959546-6bc07377-6716-473f-9051-5fa66524d13c.webm)
=> Implemented logic to display an alert before route change(#2ymay5f)

src/views/PurchaseOrder.vue
Closes #79 
The uploaded file name is not seen clearly. The change moves the file name towards the right, beside the Upload button, improving its visibility. 
=> Updated the position of file name label (#31fu19p)

src/views/PurchaseOrder.vue
Closes #107 
To prevent confusion for the user, When applying any mapping, the selected mapping name should not be set to Create new mapping input field.
https://user-images.githubusercontent.com/62360781/205057928-ab230e9e-5aa9-4ba4-9098-1c7ffd3a03de.mov
=> Fixed: Create new mapping should not show currently selected mapping name(#326r8mq)

src/views/PurchaseOrder.vue
Closes #102 
Earlier user was able to select a saved mapping even when file was not uploaded first, which was unuseful. This is fixed now.
https://user-images.githubusercontent.com/62360781/205050386-dbf58882-ba65-47ee-a229-a1bfb3455114.mov
=> Fixed: User should not be able to select a mapping before uploading a file(#326r315)

src/views/PurchaseOrder.vue
Closes #110 
Now user can only save mapping if file is uploaded, a mapping name is provided & all fields are selected.
https://user-images.githubusercontent.com/62360781/205568757-06defc43-3bf1-4e1c-8c56-4ad18d764c1b.mov
=> Fixed: SAVE MAPPING button saves empty mapping when file not uploaded(#326re7p)

src/views/PurchaseOrder.vue
Closes #
As the type for `file` variable has been changed from string to object, hence changed the disabled logic to use content length.
=> Fixed: disable logic to use length of content instead of using file variable(#85zrhcq56)

src/components/PurchaseOrderDetail.vue, src/views/PurchaseOrderReview.vue
=> Fix select deselect on purchase order detail page

src/locales/en.json, src/views/PurchaseOrderReview.vue
=> fix: search not working on PO review page(#85zrmf7ed)

src/components/MissingSkuModal.vue
Additional Changes:
fix: product should update on enter
fix: sku not updating in completed tab(#85zrpv6dd)
Closes #198  #199 
=> added: extra product info in missing sku modal

src/views/Inventory.vue, src/views/PurchaseOrder.vue
Closes #204 
[Screencast from 03-04-23 06:04:42 PM IST.webm](https://user-images.githubusercontent.com/59442907/229511001-26675062-1fb3-47d9-a2f8-6d4f4fade133.webm)
=> Implemented: toast and button disabling in case of invalid CSV upload (#85zrv53ft)

src/components/PurchaseOrderDetail.vue, src/store/modules/order/actions.ts, src/store/modules/stock/actions.ts, src/views/InventoryReview.vue
After a missing product has been mapped with a product in the system, the old value that caused the error should still be visible in the secondary text slot so that users can reconcile their data with the original uploaded data.
Closes #200 
=> Improved: Show old missing SKU value (#200)

src/components/Menu.vue
Related Issues: https://github.com/hotwax/dxp-components/issues/122
Fixed issue of menu not being enabled for the correct page when using the back button in Import app.
- Removed a watcher from the menu component that checks for route changes.
- Defined a computed property to find the correct index in the menu list.
- Added an entry in the menu component pages to list all the child routes those are not listed in the menu for a specific parent route, using which we have enabled the correct menu in the UI.
- Added a logic for the dynamic child routes in the app.
=> Implemented: Page Selection Persistence for Import App with Side Navigation(#122)

src/views/PurchaseOrderReview.vue
Closes #229
Added horizontal scrollability in bottom bar on the purchase order review page 
Before
After
[Screencast from 05-10-23 11:02:51 AM IST.webm](https://github.com/hotwax/import/assets/69574321/764b63db-82cc-499a-b5c8-9dd4fe626668)
=> Fixed: scrollability in bottom bar on purchase order review page (#229)

src/components/MissingFacilitiesModal.vue
Closes #234 
In this modification, the :disabled attribute is bound to the expression !Object.keys(itemsByFacilityId).length. When itemsByFacilityId is an empty object (no facilities), the expression evaluates to true, disabling the button. When there are facilities in the itemsByFacilityId object (at least one key), the expression evaluates to false, enabling the button.
=> Save button updated

src/mixins/parseFileMixin.ts
Related Issue #267 
Removed: unused check for file inside the mixin, as the same check is added before calling the mixin method
Removed: success and error toast message from the mixin as the toast message are already available on component level, and added them at component level will help in handling the case when unable to access 0th index of content when parsing is not performed properly
=> Fixed: duplicate toast message on file upload(#267)

src/services/UploadService.ts, src/utils/index.ts, src/views/InventoryReview.vue, src/views/PurchaseOrderReview.vue
Added: support to parse json to csv before upload
Added check for error message in api and display a toast message in both inventory and po upload case
Related Issue #279 
Changed the file from json to csv format before uploading as multi-threading does not support processing of json files.
Does not made this change for PurchaseOrder upload case as for now we do not enable multithreading support for po's as discussed.
=> Improved: support to upload csv file when updating inventory(#279)

src/store/modules/stock/actions.ts
#
- Added check to create products information based on the identification selected
- Fixed issue when getting location for facility, as location information is stored based on facilityId and not externalFacilityId
=> Fixed: issue when rendering products information on the inventory review page

src/store/modules/stock/actions.ts, src/views/ScheduledRestock.vue, src/views/ScheduledRestockReview.vue
#291 
- Correct the payload of fetching the Jobs , so now the jobs are filtering on the basis of runTime.
- Added `empty state` class on the scheduled restock review page , when no products found. 
- Added css for the filters section to the max-width.
=> Fixed: Jobs now filtered on the basis of runTime(#291)

src/components/CreateMappingModal.vue, src/views/Inventory.vue, src/views/PurchaseOrder.vue, src/views/ScheduledRestock.vue
#295
Implemented logic to highlight the selected mapping chips for better user experience.
=> Implemented: logic to highlight the selected mapping chip (#295)

src/components/CreateMappingModal.vue, src/store/modules/user/actions.ts
#166 
#
Improved: Removed generating  mapping id from client side when creating a new mapping (#166).
=> Improved: Removed generating  mapping id from client side when creating a new mapping (#166).

src/components/CreateMappingModal.vue, src/views/AdjustInventory.vue, src/views/Inventory.vue, src/views/ScheduledRestock.vue
#314
- Previously, the default product identifier was SHOPIFY_PROD_SKU. Now, SKU is set as the default product identifier across all pages.
=> Improved: Added SKU as the default product identifier in dropdowns across all pages (#314)

src/views/InventoryReview.vue, src/views/PurchaseOrderReview.vue
#320 
- After returning from the `Review` page to the `Inventory Upload` page and clicking the `Back` button, it navigates back to the `Review` page instead of the `Unified Inventory` page.  
- Added a fix by using the `go` method when navigating to the `Upload` page instead of `push`, because the `push` method stores the route history, which I believe is causing this issue.
=> Improved: Added a fix by changing the router method for navigation(#320)

src/views/AdjustInventoryHistory.vue
#325 
- Previously, when multithreading was set to ``Y``, users could change the mode to ``Sync`` from the view history page, which caused conflicts between file uploads and service execution.  
- Now, I have added a check to hide the ``Sync`` option in the mode selection when multithreading is ``Y``.
=> Improved: Added a check to hide the Sync mode option when multithreading is set to 'Y' (#325)

src/views/Inventory.vue
#322 
- On the ``Exact ATP``, ``Exact QOH``, and ``Cycle Count`` pages, previously, the field list was not visible until the CSV contained data. Now, a check has been added to keep them disabled instead.
=> Improved: Added a check to disable the field list in column mapping (#322)
